config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[new create show]
    end
  end
  get 'profile', to: 'users#edit_profile', as: :edit_profile
  patch 'profile', to: 'users#update_profile', as: :update_profile

  resources :bookings, only: %i[index show] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index new create]
  end

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  has_many :bookings, foreign_key: 'author_id'
  has_many :services
  has_many :categories, through: :services
  accepts_nested_attributes_for :services
  has_one_attached :photo
  has_many :sent_conversations, foreign_key: :sender_id, class_name: 'Conversation'
  has_many :received_conversations, foreign_key: :recipient_id, class_name: 'Conversation'
  has_many :messages, through: :conversations
  has_many :reviews, through: :bookings

  enum :status, { visible: 0, invisible: 1 }, default: :visible

  validates :status, inclusion: { in: statuses.keys }
  validates :balance, numericality: { greater_than_or_equal_to: 0 }

  def conversations
    Conversation.where("sender_id = ? OR recipient_id = ?", id, id)
  end

  def messages
    Message.where(conversation: conversations)
  end

  def city_coordinates
    Geocoder.coordinates(self.city)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_user, only: %i[edit_profile update_profile]

  def index
    @users = User.all
    @users_count = {}

    if params[:category].present?
      category = Category.find_by(name: params[:category])
      @users = @users.joins(:services).where(services: { category_id: category.id }) if category
    end

    if params[:city].present?
      @users = @users.where(city: params[:city])
    else
      @users_count = @users.group_by { |user| user.city }.transform_values(&:count)
      @users = @users.where(city: @users_count.keys)
    end

      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window: render_to_string(partial: "info_window", locals: { user: user }),
          marker_html: render_to_string(partial: "marker")
        }
      end
    @users = @users.distinct
  end

  def show
    @booking = Booking.new
    @user = User.find(params[:id])
    @bookings = Booking.joins(:service).where(services: { user: @user }).joins(:reviews)
    @users_count = {}
    @markers = [{
      lat: @user.latitude,
      lng: @user.longitude,
      info_window: render_to_string(partial: "info_window", locals: { user: @user }),
      marker_html: render_to_string(partial: "marker")
    }]
  end


  def edit_profile
    @categories = Category.all.order(:name)
  end

  def update_profile
    if @user.update(user_params)
      redirect_to edit_profile_path, notice: 'Profil mis à jour avec succès.'
    else
      @categories = Category.all.order(:name)
      render :edit_profile
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :city, :description, category_ids: [])
  end
end

app/views/users/_info_window.html.erb
<div class="info-window ">
  <h3> <%= user.city %></h3>
<p>Utilisateur<%= 's' if @users_count[user.city].to_i > 1 %> ici : <%= @users_count[user.city] %></p>
</div>
  

app/views/users/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/users/edit_profile.html.erb
<div class="container my-3">
  <%= simple_form_for @user, url: update_profile_path, method: :patch do |f| %>
    <h2 class="mt-5">Mes informations</h2>
    <%= f.input :first_name, label: 'Prénom' %>
    <%= f.input :last_name, label: 'Nom de famille' %>
    <%= f.input :city, label: 'Ville' %>
    <%= f.input :description, label: 'Description' %>

    <h2 class="mt-5">Mes services</h2>

    <% @categories.each do |category| %>
      <div class="form-check">
        <%= f.check_box :category_ids, {
          multiple: true,
          id: "categories_#{category.id}",
          class: 'form-check-input'
        }, category.id, nil %>
        <%= f.label :category_ids, category.name,
          for: "categories_#{category.id}",
          class: 'form-check-label' %>
      </div>
    <% end %>

    <%= f.submit "Mettre à jour le profil", class: 'btn btn-primary mt-5' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container my-3">
  <%= render 'shared/search_form' %>

  <h2 class="mt-5">Utilisateurs correspondants :</h2>
  <div class="cards-user mt-3 mb-5">
    <% if @users.empty? %>
      <p>Aucun utilisateur ne correspond à ta recherche.</p>
    <% end %>
    <% @users.each do |user| %>
      <%= link_to user_path(user), class: "card-user" do %>
        <% avatar = (user.photo.attached? ? user.photo : "random_user.png") %>
        <%= image_tag avatar %>
        <div class="card-user-infos">
          <h2><%= user.first_name %> <%= user.last_name %></h2>
          <p><%= user.city %></p>
          <p>
            <% categories = user.services.joins(:category).pluck('categories.name').sort %>
            <% special_category = params[:category].presence %>
            <% categories = categories.partition { |c| c == special_category }.flatten %>
            <% categories.first(3).each do |category| %>
              <% badge_color = category == special_category ? 'text-bg-warning' : 'text-bg-primary' %>
              <%= content_tag(:span, category, class: "badge fw-medium #{badge_color}") %>
            <% end %>
            <% if (additional = categories.size - 3) > 0 %>
              <span class="badge fw-medium text-bg-secondary"
                    data-bs-toggle="tooltip"
                    title="<%= categories.drop(3).join(', ') %>"
              >
                + <%= additional %> autre<%= 's' if additional > 1 %> catégorie<%= 's' if additional > 1 %>
              </span>
            <% end %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if !params[:city].present? %>
    <h2 class="pt-3"><%= @users.count %> utilisateurs correspondants à votre recherche !</h2>
    <div class= "map my-3 rounded-5 border shadow overflow-hidden">
      <div style="width: 100%; height: 600px; "
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" >
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container my-3">
  <%= link_to "Retour à la liste des utilisateurs", request.referrer || users_path, class: "btn btn-outline-primary mt-5" %>
  <div class="d-flex my-3">
    <div class="align-items-center bg-white card col-4 d-flex flex-column my-3 shadow">
      <h2 class="my-3"><%= @user.first_name.capitalize %> <%= @user.last_name.upcase %></h2>
      <% avatar = (@user.photo.attached? ? @user.photo : "random_user.png") %>
      <%= image_tag avatar, class: "border border-2 border-primary rounded-circle w-50" %>

      <div class="align-items-center card-body d-flex flex-column text-center w-75">
        <p><i class="fa-solid fa-quote-left"></i> <%= @user.description %> <i class="fa-solid fa-quote-right"></i></p>
        <p><i class="fa-solid fa-location-dot"></i> <%= @user.city %></p>
        <div class= "map col-4 mb-5 rounded-5 border shadow overflow-hidden" >
          <div style="width: auto; height: 200px; "
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
        <p><%= @user.categories.pluck(:name).sort.join(', ') %></p>
        <%= link_to "Réserver un service", new_user_booking_path(@user), class: 'btn btn-primary' %>

        <% if current_user %>
          <%= link_to 'Contacter', conversations_path(sender_id: current_user.id, recipient_id: @user.id), "data-turbo-method": :post, class: 'btn btn-primary my-3'  %>
        <% else %>
          <%= link_to 'Contacter', new_user_session_path, class: 'btn btn-primary my-3' %>
        <% end %>
      </div>
    </div>

    <div class="card bg-white col m-3 shadow">
      <div class="card-body">
        <h2 class="text-center">Avis sur l'utilisateur</h2>
        <% if @bookings.empty? %>
          <p class="mt-5">Pas d'avis sur <strong><%= @user.first_name %></strong> pour le moment !</p>
        <% else %>
          <ul class="list-group list-group-flush" style= "overflow-y: scroll;">
            <% reviews = @bookings.reverse.map { |booking| booking.reviews.first } %>
            <% reviews.sort_by { |review| review.created_at}.reverse.each do |review| %>
              <li class="bg-white list-group-item">
                <div class="d-flex">
                  <% avatar = (review.author.photo.attached? ? review.author.photo : "random_user.png") %>
                  <%= image_tag avatar, class: "avatar-mini me-3", style: "width: 50px; height: 50px;" %>
                  <div class="w-100">
                    <div class="d-flex justify-content-between">
                      <p class="mb-0">
                        <strong>
                          <%= link_to user_path(review.author), class: "text-decoration-none" do %>
                            <%= review.author.first_name.capitalize %> <%= review.author.last_name.upcase %>
                          <% end %>
                        </strong>
                      </p>
                      <p class="mb-0"><small>Posté le <%= review.created_at.strftime("%d/%m/%Y à %H:%M") %></small></p>
                    </div>
                    <p class="mb-0">
                      <%= content_tag(:span, review.booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
                      <% case review.booking.difficulty %>
                      <% when 'easy' %>
                        <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
                      <% when 'normal' %>
                        <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
                      <% when 'hard' %>
                        <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
                      <% end %>
                      <span class="mb-0 float-end">
                        <%= (review.rating.times.map { '<i class="fa-solid fa-star"></i>' } + (5 - review.rating).times.map { '<i class="fa-regular fa-star"></i>' }).join.html_safe %>
                      </span>
                    </p>
                  </div>
                </div>
                <p class="mt-3 mb-0"><%= review.comment %></p>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>