config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[new create show]
    end
  end
  get 'profile', to: 'users#edit_profile', as: :edit_profile
  patch 'profile', to: 'users#update_profile', as: :update_profile

  resources :bookings, only: %i[index show] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index new create]
  end

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'pages#dashboard'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <div class="footer mt-5">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright text-white">
        Fait avec ❤️ par la team MangoGather 🥭 pour Le Wagon
      </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="align-items-center navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item btn btn-primary">
            <%= link_to "Accueil", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item btn btn-primary">
            <%= link_to "Mes Mangu'Aides", dashboard_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item btn btn-primary">
            <%= link_to "Mes Messages", conversations_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item btn pe-none">
            <div class="nav-link text-white">Solde: <%= current_user.balance %>🥭</div>
          </li>
          <li class="nav-item dropdown">
            <% avatar = (current_user.photo.attached? ? current_user.photo : "random_user.png") %>
            <%= image_tag avatar, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end bg-white" aria-labelledby="navbarDropdown">
              <%= link_to "Editer mon profil", edit_profile_path, class: "dropdown-item" %>
              <%= link_to "Paramètres", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item d-flex">
            <%= link_to "S'enregistrer", new_user_registration_path, class: "nav-link text-white btn btn-primary" %>
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-white btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<h2 class="mt-5">Rechercher un service</h2>

<%= simple_form_for :search, url: search_path, method: :get, html: { class: 'd-flex mt-3' } do |f| %>
  <div class='col flex-grow-1 me-2'>
    <%= f.input :city,
                required: false,
                label: false,
                as: :string,
                input_html: {
                              name: 'city',
                              class: 'bg-white form-control',
                              placeholder: 'Ville : Paris, Toulouse, ...',
                              value: params[:city]
                            }
    %>
  </div>
  <div class="col flex-grow-1 me-2">
    <%= f.input :category,
                label: false,
                required: false,
                collection: Category.all.map(&:name),
                selected: params[:category],
                include_blank: 'Catégorie : Bricolage, Informatique, ...',
                wrapper: false,
                label_html: { class: 'visually-hidden' },
                input_html: { name: 'category', class: 'bg-white form-select' }
    %>
  </div>
  <div class="col-auto">
    <%= f.button :submit, 'Rechercher', class: 'btn btn-primary px-5' %>
  </div>
<% end %>