config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[new create show]
    end
  end
  get 'profile', to: 'users#edit_profile', as: :edit_profile
  patch 'profile', to: 'users#update_profile', as: :update_profile

  resources :bookings, only: %i[index show] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index new create]
  end

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'pages#dashboard'
end

app/views/pages/_info_window.html.erb
<div class="info-window ">
  <h3> <%= user.city %></h3>
  <p>Utilisateur<%= 's' if @users_count[user.city] > 1 %> ici : <%= @users_count[user.city] %></p>
</div>

app/views/pages/_marker.html.erb
<%= image_tag "marker.png", height: 30, width: 30, alt: "Logo" %>

app/views/pages/dashboard.html.erb
<div class="container my-3">
  <h2 class="mt-5">Demandes de services</h2>
  <% if @bookings.empty? %>
    <p>Aucune demande de réservation reçue pour le moment.</p>
  <% end%>
  <% @bookings.each do |booking| %>
    <% if booking.pending? || booking.approved? %>
      <div class="notification my-3">
        <% author = booking.author %>
        <% avatar = (author.photo.attached? ? author.photo : "random_user.png") %>
        <%= image_tag avatar, class: "avatar-large" %>
        <div class="d-flex flex-column flex-grow-1">
          <div class="notification-content">
            <p><small><%= booking.created_at.strftime("%d/%m/%Y à %H:%M") %></small></p>
            <p><strong><%= author.first_name.capitalize %> <%= author.last_name.upcase %></strong></p>
            <p>
              Souhaite réserver un service
              <%= content_tag(:span, booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
              <% case booking.difficulty %>
              <% when 'easy' %>
                <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
              <% when 'normal' %>
                <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
              <% when 'hard' %>
                <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
              <% end %>
              , le <strong><%= booking.date.strftime("%d/%m/%Y à %H:%M") %></strong>,
              pour un gain de <%= booking.price %>🥭 !
            </p>
          </div>
          <div class="notification-actions d-flex gap-3 justify-content-center my-3">
            <% case %>
              <% when booking.pending? %>
                <%= button_to 'Accepter', accept_booking_path(booking), method: :patch, class: 'btn btn-outline-success px-5' %>
                <%= button_to 'Refuser', decline_booking_path(booking), method: :patch, class: 'btn btn-outline-danger px-5' %>
              <% when booking.approved? %>
                <button class='btn btn-success disabled'>Acceptée</button>
              <% when booking.declined? %>
                <button class='btn btn-danger disabled'>Refusée</button>
            <% end %>
          </div>
        </div>
      </div>
    <%end%>
  <% end %>

  <h2 class="mt-5">Demandes de services refusées</h2>
  <% if @bookings.empty? %>
    <p>Aucune demande de réservation reçue pour le moment.</p>
  <% end%>
  <% @bookings.each do |booking| %>
    <% if booking.declined? %>
      <div class="notification my-3">
        <% user = booking.author %>
        <div class="text-center" style="width: 20%;">
          <div class='btn btn-danger disabled w-100'>Refusée</div>
        </div>
        <div class="d-flex flex-column flex-grow-1">
          <div class="notification-content">
            <p><small>Créée le <%= booking.created_at.strftime("%d/%m/%Y à %H:%M") %></small></p>
            <p>
              <strong>
                <%= link_to user_path(user), class: "text-decoration-none" do %>
                  <%= user.first_name.capitalize %> <%= user.last_name.upcase %>
                <% end %>
              </strong>
              souhaitait réserver un service
              <%= content_tag(:span, booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
              <% case booking.difficulty %>
              <% when 'easy' %>
                <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
              <% when 'normal' %>
                <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
              <% when 'hard' %>
                <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
              <% end %>
              , </strong> le <strong><%= booking.date.strftime("%d/%m/%Y à %H:%M") %></strong>
              pour un gain de <%= booking.price %>🥭 !
            </p>
          </div>
        </div>
      </div>
    <%end%>
  <% end %>


  <h2 class="mt-5">Mes demandes de réservation émises</h2>
  <% if @authored_bookings.empty? %>
    <p>Aucune demande de réservation effectuée pour le moment.</p>
  <% end%>
  <% @authored_bookings.each do |authored_booking| %>
    <% if authored_booking.approved? || authored_booking.pending? %>
      <div class="notification my-3">
        <% user = authored_booking.service.user %>
        <% if authored_booking.approved? %>
          <% if authored_booking.reviews.empty? %>
            <div class="w-25"><%= link_to 'Publier un avis', new_user_booking_review_path(user_id: current_user, booking_id: authored_booking.id), class: 'btn btn-primary w-100' %></div>
          <% else %>
            <div class="w-25"><div class='btn btn-outline-primary disabled w-100'>Avis déjà publié</div></div>
          <% end %>
        <% elsif authored_booking.pending? %>
          <div class="d-flex flex-column w-25 text-center">
            <div class='btn btn-primary disabled w-100'>Publier un avis</div>
            <small class="mt-2">Disponible dès que la réservation sera acceptée</small>
          </div>
        <% end %>
        <div class="d-flex flex-column flex-grow-1">
          <div class="notification-content">
            <p><small>Créée le <%= authored_booking.created_at.strftime("%d/%m/%Y à %H:%M") %></small></p>
            <p>
              Demande de réservation auprès de
              <strong>
                <%= link_to user_path(user), class: "text-decoration-none" do %>
                  <%= user.first_name.capitalize %> <%= user.last_name.upcase %>
                <% end %>
              </strong>
              pour un service
              <%= content_tag(:span, authored_booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
              <% case authored_booking.difficulty %>
              <% when 'easy' %>
                <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
              <% when 'normal' %>
                <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
              <% when 'hard' %>
                <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
              <% end %>
              , à <strong><%= user.city %> </strong> le <strong><%= authored_booking.date.strftime("%d/%m/%Y à %H:%M") %></strong>
              pour un coût de <%= authored_booking.price %>🥭 !
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <h2 class="mt-5">Mes demandes de réservation refusées</h2>
  <% @authored_bookings.each do |authored_booking| %>
    <% if authored_booking.declined? %>
      <div class="notification my-3">
        <% user = authored_booking.service.user %>
        <div class="text-center" style="width: 25%;">
          <div class='btn btn-danger disabled w-100'>Refusée</div>
        </div>
        <div class="d-flex flex-column flex-grow-1">
          <div class="notification-content">
            <p><small>Créée le <%= authored_booking.created_at.strftime("%d/%m/%Y à %H:%M") %></small></p>
            <p>
              Demande de réservation auprès de
              <strong>
                <%= link_to user_path(user), class: "text-decoration-none" do %>
                  <%= user.first_name.capitalize %> <%= user.last_name.upcase %>
                <% end %>
              </strong>
              pour un service
              <%= content_tag(:span, authored_booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
              <% case authored_booking.difficulty %>
              <% when 'easy' %>
                <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
              <% when 'normal' %>
                <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
              <% when 'hard' %>
                <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
              <% end %>
              , à <strong><%= user.city %> </strong> le <strong><%= authored_booking.date.strftime("%d/%m/%Y à %H:%M") %></strong>
              pour un coût de <%= authored_booking.price %>🥭 !
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_path('banner.png') %>');">
  <div class="container">
    <h1>Mangogather, l’ingrédient manquant pour sublimer ton quotidien !</h1>
  </div>
</div>

<div class="container">
  <%= render 'shared/search_form' %>
  <h2 class="mt-5">Catégories disponibles</h2>
  <div class="cards mt-3">
    <% Category.all.each do |category| %>
      <% img = (category.photo.attached? ? url_for(category.photo) : asset_path('category_placeholder.png')) %>
      <%= link_to "/users?category=#{category.name}" do %>
        <div class="card">
          <div class="card-body">
            <img src="<%= img %>" alt="">
            <p><%= category.name %></p>
          </div>
        </div>
      <%end%>
    <% end %>
    <% img = asset_path('category_placeholder.png') %>
    <%= link_to "/users" do %>
      <div class="card mb-5">
        <div class="card-body">
          <img src="<%= img %>" alt="">
          <p>Tous les utilisateurs</p>
        </div>
      </div>
    <%end%>
  </div>
  <h2 class="mt-4">Mangogather est présent dans <%= @users_count.count %> villes !</h2>
  <div class= "map my-3 rounded-5 border shadow overflow-hidden">
    <div style="width: 100%; height: 600px; "
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" >
    </div>
  </div>
</div>