config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[new create show]
    end
  end
  get 'profile', to: 'users#edit_profile', as: :edit_profile
  patch 'profile', to: 'users#update_profile', as: :update_profile

  resources :bookings, only: %i[index show] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index new create]
  end

  get 'search', to: 'pages#search'
  get 'dashboard', to: 'pages#dashboard'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.author = current_user

    if @booking.approved?
      @review.booking = @booking

      if @review.save
        redirect_to dashboard_path, notice: 'Review créée avec succès.'
      else
        render :new
      end
    else
      redirect_to root_path, alert: 'Impossible de créer une review pour un booking non accepté.'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class= "container my-3">
  <h2 class="mt-5">Publier mon avis</h2>
  <p class="my-3">
    Petit rappel, tu dois noter
    <strong><%= @booking.service.user.first_name.capitalize %> <%= @booking.service.user.last_name.upcase %></strong>
    pour le service
    <%= content_tag(:span, @booking.service.category.name, class: "badge fw-medium text-bg-primary") %>
    <% case @booking.difficulty %>
    <% when 'easy' %>
      <%= content_tag(:span, 'Difficulté facile', class: "badge fw-medium text-bg-success") %>
    <% when 'normal' %>
      <%= content_tag(:span, 'Difficulté moyenne', class: "badge fw-medium text-bg-warning") %>
    <% when 'hard' %>
      <%= content_tag(:span, 'Difficulté difficile', class: "badge fw-medium text-bg-danger") %>
    <% end %>
    , du <strong><%= @booking.date.strftime("%d/%m/%Y à %H:%M") %></strong> à <strong><%= @booking.service.user.city %> </strong>
    pour un coût de <%= @booking.price %>🥭 !
  </p>

  <%= simple_form_for @review, url: user_booking_reviews_path, method: :post, html: { class: 'form-horizontal my-3' } do |form| %>
    <%= form.input :rating, label: 'Note (0 = mauvais, 5 = parfait)', input_html: { class: 'form-control bg-white', required: true, min: 0, max: 5 }, as: :integer %>
    <%= form.input :comment, label: 'Commentaire', as: :text, input_html: { class: 'form-control bg-white', required: true } %>
    <%= form.button :submit, 'Publier', class: 'btn btn-primary mt-3' %>
  <% end %>
</div>